import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--app-bg)",
        foreground: "var(--app-text)",
        card: {
          DEFAULT: "var(--app-card-bg)",
          foreground: "var(--app-text)",
        },
        popover: {
          DEFAULT: "var(--app-card-bg)",
          foreground: "var(--app-text)",
        },
        primary: {
          DEFAULT: "var(--app-accent)",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "var(--app-elevated)",
          foreground: "var(--app-text)",
        },
        muted: {
          DEFAULT: "var(--app-elevated)",
          foreground: "var(--app-text-muted)",
        },
        accent: {
          DEFAULT: "var(--app-accent-light)",
          foreground: "var(--app-accent)",
        },
        destructive: {
          DEFAULT: "var(--app-danger)",
          foreground: "#ffffff",
        },
        border: "var(--app-border)",
        input: "var(--app-input-bg)",
        ring: "var(--app-accent)",
        chart: {
          "1": "var(--app-module-erp)",
          "2": "var(--app-module-crm)",
          "3": "var(--app-module-analytics)",
          "4": "var(--app-module-finance)",
          "5": "var(--app-module-marketing)",
        },
        app: {
          bg: "var(--app-bg)",
          "card-bg": "var(--app-card-bg)",
          "card-bg-hover": "var(--app-card-bg-hover)",
          elevated: "var(--app-elevated)",
          "input-bg": "var(--app-input-bg)",
          accent: "var(--app-accent)",
          "accent-hover": "var(--app-accent-hover)",
          "accent-light": "var(--app-accent-light)",
          text: "var(--app-text)",
          "text-secondary": "var(--app-text-secondary)",
          "text-muted": "var(--app-text-muted)",
          "text-disabled": "var(--app-text-disabled)",
          border: "var(--app-border)",
          "border-light": "var(--app-border-light)",
          "border-strong": "var(--app-border-strong)",
          "hover-bg": "var(--app-hover-bg)",
          "active-bg": "var(--app-active-bg)",
          success: "var(--app-success)",
          warning: "var(--app-warning)",
          danger: "var(--app-danger)",
          info: "var(--app-info)",
          "success-bg": "var(--app-success-bg)",
          "warning-bg": "var(--app-warning-bg)",
          "danger-bg": "var(--app-danger-bg)",
          "info-bg": "var(--app-info-bg)",
          overlay: "var(--app-overlay)",
          "sidebar-bg": "var(--app-sidebar-bg)",
          "topbar-bg": "var(--app-topbar-bg)",
        },
      },
      borderRadius: {
        sm: "var(--app-radius-sm)",
        md: "var(--app-radius-md)",
        lg: "var(--app-radius-lg)",
        xl: "var(--app-radius-xl)",
        "2xl": "var(--app-radius-xl)",
        full: "var(--app-radius-full)",
      },
      boxShadow: {
        sm: "var(--app-shadow-sm)",
        md: "var(--app-shadow-md)",
        card: "var(--app-shadow-card)",
        "card-hover": "var(--app-shadow-card-hover)",
        dropdown: "var(--app-shadow-dropdown)",
        modal: "var(--app-shadow-modal)",
        accent: "var(--app-shadow-accent)",
      },
      spacing: {
        "app-xs": "var(--app-space-xs)",
        "app-sm": "var(--app-space-sm)",
        "app-md": "var(--app-space-md)",
        "app-lg": "var(--app-space-lg)",
        "app-xl": "var(--app-space-xl)",
        "app-2xl": "var(--app-space-2xl)",
        "app-3xl": "var(--app-space-3xl)",
        "app-4xl": "var(--app-space-4xl)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
export default config;
