import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--app-bg)",
        foreground: "var(--app-text)",
        card: {
          DEFAULT: "var(--app-card-bg)",
          foreground: "var(--app-text)",
        },
        popover: {
          DEFAULT: "var(--app-card-bg)",
          foreground: "var(--app-text)",
        },
        primary: {
          DEFAULT: "var(--app-accent)",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "var(--app-elevated)",
          foreground: "var(--app-text)",
        },
        muted: {
          DEFAULT: "var(--app-elevated)",
          foreground: "var(--app-text-muted)",
        },
        accent: {
          DEFAULT: "var(--app-accent-light)",
          foreground: "var(--app-accent)",
        },
        destructive: {
          DEFAULT: "var(--app-danger)",
          foreground: "#ffffff",
        },
        border: "var(--app-border)",
        input: "var(--app-input-bg)",
        ring: "var(--app-structural)",
        chart: {
          "1": "var(--app-module-erp)",
          "2": "var(--app-module-crm)",
          "3": "var(--app-module-analytics)",
          "4": "var(--app-module-finance)",
          "5": "var(--app-module-marketing)",
        },
        app: {
          bg: "var(--app-bg)",
          "card-bg": "var(--app-card-bg)",
          "card-bg-hover": "var(--app-card-bg-hover)",
          elevated: "var(--app-elevated)",
          "input-bg": "var(--app-input-bg)",
          accent: "var(--app-accent)",
          "accent-hover": "var(--app-accent-hover)",
          "accent-light": "var(--app-accent-light)",
          "accent-glow": "var(--app-accent-glow)",
          structural: "var(--app-structural)",
          "structural-hover": "var(--app-structural-hover)",
          "structural-light": "var(--app-structural-light)",
          "structural-glow": "var(--app-structural-glow)",
          blue: "var(--app-blue)",
          "blue-hover": "var(--app-blue-hover)",
          "blue-light": "var(--app-blue-light)",
          "blue-glow": "var(--app-blue-glow)",
          orange: "var(--app-orange)",
          "orange-hover": "var(--app-orange-hover)",
          "orange-light": "var(--app-orange-light)",
          "orange-glow": "var(--app-orange-glow)",
          text: "var(--app-text)",
          "text-secondary": "var(--app-text-secondary)",
          "text-muted": "var(--app-text-muted)",
          "text-disabled": "var(--app-text-disabled)",
          border: "var(--app-border)",
          "border-light": "var(--app-border-light)",
          "border-strong": "var(--app-border-strong)",
          "border-accent": "var(--app-border-accent)",
          "hover-bg": "var(--app-hover-bg)",
          "active-bg": "var(--app-active-bg)",
          "pressed-bg": "var(--app-pressed-bg)",
          success: "var(--app-success)",
          warning: "var(--app-warning)",
          danger: "var(--app-danger)",
          info: "var(--app-info)",
          "success-bg": "var(--app-success-bg)",
          "warning-bg": "var(--app-warning-bg)",
          "danger-bg": "var(--app-danger-bg)",
          "info-bg": "var(--app-info-bg)",
          overlay: "var(--app-overlay)",
          "overlay-heavy": "var(--app-overlay-heavy)",
          "glass-bg": "var(--app-glass-bg)",
          "sidebar-bg": "var(--app-sidebar-bg)",
          "topbar-bg": "var(--app-topbar-bg)",
          "surface-0": "var(--app-surface-0)",
          "surface-1": "var(--app-surface-1)",
          "surface-2": "var(--app-surface-2)",
          "surface-3": "var(--app-surface-3)",
          "surface-4": "var(--app-surface-4)",
          divider: "var(--app-divider)",
          "chip-bg": "var(--app-chip-bg)",
          "chip-border": "var(--app-chip-border)",
          purple: "var(--app-purple)",
          "purple-light": "var(--app-purple-light)",
          emerald: "var(--app-emerald)",
          "emerald-light": "var(--app-emerald-light)",
        },
      },
      borderRadius: {
        xs: "var(--app-radius-xs)",
        sm: "var(--app-radius-sm)",
        md: "var(--app-radius-md)",
        lg: "var(--app-radius-lg)",
        xl: "var(--app-radius-xl)",
        "2xl": "var(--app-radius-2xl)",
        full: "var(--app-radius-full)",
      },
      boxShadow: {
        sm: "var(--app-shadow-sm)",
        md: "var(--app-shadow-md)",
        card: "var(--app-shadow-card)",
        "card-hover": "var(--app-shadow-card-hover)",
        dropdown: "var(--app-shadow-dropdown)",
        modal: "var(--app-shadow-modal)",
        accent: "var(--app-shadow-accent)",
        blue: "var(--app-shadow-blue)",
        "glow-blue": "var(--app-shadow-glow-blue)",
        "glow-orange": "var(--app-shadow-glow-orange)",
      },
      spacing: {
        "app-0": "var(--app-space-0)",
        "app-0-5": "var(--app-space-0-5)",
        "app-xs": "var(--app-space-xs)",
        "app-sm": "var(--app-space-sm)",
        "app-md": "var(--app-space-md)",
        "app-lg": "var(--app-space-lg)",
        "app-xl": "var(--app-space-xl)",
        "app-2xl": "var(--app-space-2xl)",
        "app-3xl": "var(--app-space-3xl)",
        "app-4xl": "var(--app-space-4xl)",
        "app-5xl": "var(--app-space-5xl)",
        "app-6xl": "var(--app-space-6xl)",
      },
      transitionTimingFunction: {
        'app': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'app-spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
};
export default config;
